### Sample secrets.toml file
[Model_url]
start_url = "Get the web url for the web inference function eg https://user--hunyuan-modal-py-web-inference-dev.modal.run"                                                                                   
result_url = "Get the web url for the get result function  https://user--hunyuan-modal-py-get-result-dev.modal.run"
cancel_url = "Get the web url for the py cancel function  https://user--hunyuan-modal-py-cancel-call-dev.modal.run"
WS_URI = "Get the web url for the log endpoint function, it will be in http but has to be formatted with wss and ws  wss://user--my-app-log-endpoint-dev.modal.run/ws" 
